// Generated by GraphWalker (http://www.graphwalker.org)
package es.udc.java.pa.pa009.pwin.model.testautomation;

import org.graphwalker.java.annotation.Edge;
import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;

@Model(file = "es/udc/pa/pa009/pwin/model/testautomation/GraphModelTest.graphml")
public interface GraphModelTest {

	@Vertex()
	void Started();

	@Edge()
	void find();

	@Vertex()
	void Eliminated();

	@Edge()
	void save();

	@Edge()
	void initialize();

	@Edge()
	void remove();

	@Vertex()
	void Created();
}
